### ISSUE TITLE
Contact import fails with characters like "/" in the phone number

### ISSUE THREAD

**Issue by skruppy** [janimo/textsecure-qml#42] opened 2016-02-05 02:36 UTC
Imported contacts from the Address Book won't show up on the TextSecure QML contact list, if the phone numer has characters like "/" in it (e.g. "+49 123 / 42 42 42"). Never the less, the contacts will end up in `contacts.yml`.

**Comment by janimo** [comment] 2016-02-05 08:28
That would be a bug indeed, since the Android client accepts such number.  I find it hard to reproduce since I can't see how one can introduce slashes in a contact number in the address book. Only digits and the + sign shows up on the keyboard.

**Comment by janimo** [comment] 2016-02-05 08:30
contacts.yml btw is a full mirror of the address book, not just Signal contacts. It is needed so that one does not need to constantly be promped for imporint the address book, but be able to sync with the server and get newly registered contacts.

**Comment by skruppy** [comment] 2016-02-05 12:55
Thats interesting. My phonebook is synced remotely. Thats how those characters come in here. Maybe its a good idea to simply remove `[^+0-9]`.

**Comment by janimo** [comment] 2016-02-05 13:21
Right, if libphonenumber does not do it itself, I'll do what you suggest manually.

**Comment by janimo** [comment] 2016-02-29 09:47
Can you check 0.3.11, it should be fixed there.

**Closed as completed** 2016-03-11 08:17 UTC
